# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        "/:title"
relative_permalinks: true

# Setup
title:            Oskar Klintrot
tagline:          'Homepage of Oskar Klintrot'
description:      'Still working on it...'
url:              http://oskarklintrot.github.io/
baseurl:          /

author:
  name:           'Oskar Klintrot'
  url:            http://oskarklintrot.se

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/OskarKlintrot/oskarklintrot.github.io
