# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet:
  # enable auto ids for redcarpet
  extensions:    ["with_toc_data"]

# Permalinks
permalink:        "pretty"

# Redirects
gems:
  - jekyll-redirect-from

# Setup
title:            Oskar Klintrot
tagline:          'Homepage of Oskar Klintrot'
description:      'CS Student'
url:              http://oskarklintrot.se
baseurl:          "/"

author:
  name:           'Oskar Klintrot'
  url:            http://oskarklintrot.se

paginate:         5
paginate_path:    "blog/page:num/"
blog_path:        "blog/"

# Posts
#excerpt_separator: <!--break-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/OskarKlintrot/oskarklintrot.se
