# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        "/:title"
relative_permalinks: true

# Setup
title:            Oskar Klintrot
tagline:          'Homepage of Oskar Klintrot'
description:      'CS Student'
url:              http://oskarklintrot.se
baseurl:          "/"
blog_path:        "blog/"

author:
  name:           'Oskar Klintrot'
  url:            http://oskarklintrot.se

paginate:         5
paginate_path:    "blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/OskarKlintrot/oskarklintrot.se
