# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        "/blog/:title"
relative_permalinks: true

# Setup
title:            Oskar Klintrot
tagline:          'Homepage of Oskar Klintrot'
description:      'CS Student'
url:              http://oskarklintrot.github.io/myblog
baseurl:          "/"

author:
  name:           'Oskar Klintrot'
  url:            http://oskarklintrot.se

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/OskarKlintrot/myblog
